
package br.com.rody.jaxwstestserver.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpregadoServiceImpl", targetNamespace = "http://service.jaxwstestserver.rody.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpregadoServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.rody.jaxwstestserver.service.Empregado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmpregadoById", targetNamespace = "http://service.jaxwstestserver.rody.com.br/", className = "br.com.rody.jaxwstestserver.service.GetEmpregadoById")
    @ResponseWrapper(localName = "getEmpregadoByIdResponse", targetNamespace = "http://service.jaxwstestserver.rody.com.br/", className = "br.com.rody.jaxwstestserver.service.GetEmpregadoByIdResponse")
    @Action(input = "http://service.jaxwstestserver.rody.com.br/EmpregadoServiceImpl/getEmpregadoByIdRequest", output = "http://service.jaxwstestserver.rody.com.br/EmpregadoServiceImpl/getEmpregadoByIdResponse")
    public Empregado getEmpregadoById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
